### ISSUE TITLE
use await

### ISSUE THREAD

**Issue by alexlin083** [azole/nodejs-mfee16#2]
https://github.com/azole/nodejs-mfee16/blob/a2105bbc6f13ac20b871c3cf37f335dbd1a3fe44/crawler/crawler.js#L23

let stockNoName = await twse.queryStockName(array[i]);

https://github.com/azole/nodejs-mfee16/blob/a2105bbc6f13ac20b871c3cf37f335dbd1a3fe44/crawler/crawler.js#L39

let stockPriceData = await twse.queryStockData(array[i]);

**Comment by azole** [comment]
thanks, fixed, close~
